# ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
# ------------------------------------------------------------

###################################################################################################
# Ingestion Secret Provider Class - CSI Driver
###################################################################################################
{{- $svcversion := .Chart.AppVersion | replace "." "" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ingestion-secrets-csi-akv-{{ $svcversion }}
  namespace: backend-dev
spec:
  provider: azure
  secretObjects:
  - secretName: ingestion-ingress-tls
    type: Opaque
    data:
    - objectName: Ingestion-Ingress-Tls-Key
      key: tls.key
    - objectName: Ingestion-Ingress-Tls-Crt
      key: tls.crt
  - secretName: ingestion-secrets
    type: Opaque
    data:
    - objectName: Queue--Key
      key: queue-keyvalue
    - objectName: ApplicationInsights--InstrumentationKey
      key: appinsights-ikey
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.identity.clientid }}
    keyvaultName: {{ .Values.keyVaultName }}
    objects:  |
      array:
        - |
          objectName: Queue--Key
          objectAlias: Queue--Key
          objectType: secret
        - |
          objectName: ApplicationInsights--InstrumentationKey
          objectAlias: ApplicationInsights--InstrumentationKey
          objectType: secret
        - |
          objectName: Ingestion-Ingress-Tls-Key
          objectAlias: Ingestion-Ingress-Tls-Key
          objectType: secret
        - |
          objectName: Ingestion-Ingress-Tls-Crt
          objectAlias: Ingestion-Ingress-Tls-Crt
          objectType: secret
    tenantId: {{ .Values.identity.tenantId }}
---
