kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  queue_keyname: {{ required "secrets.queue.keyname is required" .Values.secrets.queue.keyname | b64enc }}
  queue_name: {{ required "secrets.queue.name is required" .Values.secrets.queue.name | b64enc }}
  queue_namespace: {{ required "secrets.queue.namespace is required" .Values.secrets.queue.namespace | b64enc }}
