# ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
# ------------------------------------------------------------

###################################################################################################
# Workflow Secret Provider Class - CSI Driver
###################################################################################################
{{- $svcversion := .Chart.AppVersion | replace "." "" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: workflow-secrets-csi-akv-{{ $svcversion }}
  namespace: backend-dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.identity.clientid }}
    keyvaultName: {{ .Values.keyvault.name }}
    objects:  |
      array:
        - |
          objectName: QueueAccessPolicyKey
          objectAlias: QueueAccessPolicyKey
          objectType: secret
        - |
          objectName: ApplicationInsights--InstrumentationKey
          objectAlias: ApplicationInsights--InstrumentationKey
          objectType: secret
    tenantId: {{ .Values.identity.tenantId }}
---
