# ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
# ------------------------------------------------------------

###################################################################################################
# Workflow Secret
###################################################################################################
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  queue_name: {{ required "secrets.queue.name is required" .Values.secrets.queue.name | b64enc }}
  queue_endpoint: {{ required "secrets.queue.endpoint is required" .Values.secrets.queue.endpoint | b64enc }}
  queue_policyname: {{ required "secrets.queue.policyname is required" .Values.secrets.queue.policyname | b64enc }}