apiVersion: v2
name: package
version: v0.1.0
appVersion: v0.1.0
description: Nho Luong Delivery Package Service
type: application
home: https://docs.microsoft.com/azure/architecture/reference-architectures/microservices/aks
sources:
  - https://github.com/nholuongut/microservices-reference-implementation
dependencies:
  - name: package-dev
    repository: "file://envs/package-dev"
    version: "v0.1.0"
    condition: envs.dev
    tags:
      - dev
    import-values:
      - data
