#  ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
#  ------------------------------------------------------------

###################################################################################################
# ingress
###################################################################################################
{{- $svcversion := .Chart.AppVersion | replace "." "" }}
{{- $appversion := .Chart.AppVersion }}
{{- $defaultversionedpath := printf "/%s/" $appversion }}
{{- $relname := .Release.Name }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $relname }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api/deliveries/public$1
spec:
  ingressClassName: {{ required "ingress.class is required" .Values.ingress.class | quote }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.hosts }}
  {{- if .tls }}
  - hosts:
    - {{ .name }}
    secretName: {{ .tlsSecretName }}
  {{- end }}
  {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      {{- if .path }}
      - path: {{ printf "%s/%s/" .path $appversion }}api/deliveries(.*)
        pathType: ImplementationSpecific
      {{- else }}
      - path: {{ $defaultversionedpath }}api/deliveries(.*)
        pathType: ImplementationSpecific
      {{- end }}
        backend:
          service:
            name: "{{ .serviceName }}-{{ $svcversion }}"
            port:
              name: http
  {{ end }}
