# ------------------------------------------------------------
#   Copyright (c) Microsoft Corporation.  All rights reserved.
#   Licensed under the MIT License (MIT). See License.txt in the repo root for license information.
# ------------------------------------------------------------

###################################################################################################
# Delivery Secret Provider Class - CSI Driver
###################################################################################################
{{- $svcversion := .Chart.AppVersion | replace "." "" }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: delivery-secrets-csi-akv-{{ $svcversion }}
spec:
  provider: azure
  secretObjects:
  - secretName: delivery-ingress-tls
    type: Opaque
    data:
    - objectName: Delivery-Ingress-Tls-Key
      key: tls.key
    - objectName: Delivery-Ingress-Tls-Crt
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.identity.clientid }}
    keyvaultName: {{ .Values.keyVaultName }}
    objects:  |
      array:
        - |
          objectName: Delivery-Ingress-Tls-Key
          objectAlias: Delivery-Ingress-Tls-Key
          objectType: secret
        - |
          objectName: Delivery-Ingress-Tls-Crt
          objectAlias: Delivery-Ingress-Tls-Crt
          objectType: secret
    tenantId: {{ .Values.identity.tenantId }}
---
